# Generated by Django 5.1.2 on 2024-10-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0004_remove_feesrecord_fee_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feesrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='libraryrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
    ]
