# Generated by Django 5.1.2 on 2024-10-26 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_libraryrecord_borrowed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryrecord',
            name='borrowed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
