# Generated by Django 5.1.2 on 2024-10-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_libraryrecord_borrowed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryrecord',
            name='status',
            field=models.CharField(default='borrowed', max_length=20),
        ),
    ]
