# Generated by Django 5.1.2 on 2024-10-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_libraryrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='curent_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
